namespace: dress-fullstack-app

# =====================
# Ingress Configuration
# =====================
ingress:
  enabled: true
  host: localhost   # or your Minikube IP if not using localhost

# =====================
# MySQL Configuration
# =====================
mysql:
  image: mysql:8.0
  rootPassword: pass
  database: dtable
  service:
    port: 3306
    type: ClusterIP

# =====================
# Backend Configuration
# =====================
backend:
  image: ruchithavemula11/backend-helm:latest
  replicas: 2
  port: 2090
  nodePort: 30040
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "256Mi"
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 50

# =====================
# Frontend Configuration
# =====================
frontend:
  image: ruchithavemula11/backend-helm:latest
  replicas: 2
  port: 80
  nodePort: 30030
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "256Mi"
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 50

  # Point frontend to backend service
  apiUrl: "/api"